### ISSUE TITLE
Add detailed command line analysis pipeline

### ISSUE THREAD

**Issue by gdurif** [diyabc/diyabc.github.io#1]
Add a page detailing the command line pipeline to run an analysis from a data file and a `header.txt` file, e.g.

```bash
diyabc -p ./ -n "'t:4'"
diyabc -p ./ -R "" -m -g 50 -r 100 -t 4
abcranger -t 1000 -j 8 --parameter N1 --chosenscen 1 --noob 50
```

Target audience: more advanced users who will quickly drop the GUI for CLI

**Comment by aestoup** [comment]
On pourrait peut etre donner pour exemple les lignes de commande que j'ai utilisé pour l'exemple MER IndSeq :


Scenario choice:

1/ pour simuler un training set avec 12000 datasets (6 scenario, 2000 datasets par scenario cf. header associé)

./diyabc ./ -R "" -r 12000 -g 50 -m -t 32
---> reftable de 12000 records avec all stats avec loopsize de 50 le tout sur 32 coeurs

2/ pour faire random forest scenario choice sur le training set obtenu via 1/ (foret de 1000 arbre)

- Sans scenario grouping

./abcranger -n 12000 -t 1000 -j 32 -o modelchoice_results_no_grouping

- Avec scenario grouping de deux groupes de 3 scenarios

./abcranger -n 12000 -t 1000 -g "1,2,3;4,5,6" -j 32 -o modelchoice_results_with_grouping


Parameter estimation:

3/ pour simuler un training set avec 10000 datasets pour un seul scenario cf. best scenario determiné via 2/  ( cf. header associé)

./diyabc ./ -R "" -r 10000 -g 50 -m -t 32
---> reftable de 10000 records avec all stats avec loopsize de 50 le tout sur 32 coeurs

4/ Pour estimer le parametre ra du scenario 1 a partir du training set obtenu via 3/ avec PLS (cf selection des n axes PLS  qui expliquent 95% de la variance)
./abcranger -n 10000 -t 1000 -j 32 --parameter ra --chosenscen 1 --plsmaxvar 0.95 --noob 10000 -o estim_param_ra_with_PLS

**Comment by fradav** [comment]
@aestoup il faut tuner les exemples pour qu'ils soient courts à executer pour un tuto, les exemples MER sont un peu longs dans l'absolu.

**Comment by fradav** [comment]
Done in https://github.com/diyabc/MER_publication_materials/tree/main/MER_2021_DATASET_EXAMPLES
