### ISSUE TITLE
Input DNA sequence locus data

### ISSUE THREAD

**Issue by heather340** [diyabc/diyabc.github.io#8]
I see in the manual that the preferred DIYABC-RF input for DNA sequence data is in the Genepop format. I will be using UCE/sequence capture data to run this analysis and haven't found a good way to convert my .phyml file to Genepop (PGDSpider?). Do you have a way that you recommend doing this? 

Thanks, 
Heather

**Comment by fradav** [comment]
After discussion with @aestoup and @elombaert, we don't know by ourselves any converter software. According to @aestoup  there is a very good chances that some people made or use such a converter but we don't have any collaborations with them, so we don't know.

**Comment by heather340** [comment]
Hi @fradav, 
Thanks for the quick response. I will try PGDSpider to convert the data over (from fasta and/or phylip) and see how that goes, although it is computationally intensive. If you come across a better way of converting the data, please let me know. I think the most difficult thing for me in learning a new process is getting the input data into the correct format! I'm sure other people will be having a similar issue at some point. 
Thanks!

**Comment by Zhaoxiurong** [comment]
I have the same problem as you. Have you found a way to convert fasta into genepop files that meet diyabc requirements?
